blank_issues_enabled: false
contact_links:
  - name: Bug report ğŸ
    url: https://github.com/iTwin/iTwinUI-react/issues/new?labels=bug&template=bug_report.md&projects=iTwin/iTwinUI-react/1
    about: Create a report to help us improve
